### ISSUE TITLE
Can you add examples for "situation", "instruction", "dialogue_history" like https://github.com/f/awesome-chatgpt-prompts ?

### ISSUE THREAD

**Issue by justlearntutors** [skywalker023/sodaverse#1]
Do you have more examples for "situation", "instruction", "dialogue_history"?
Like https://github.com/f/awesome-chatgpt-prompts

situation_narrative = "Cosmo is having a friendly conversation with a friend."
role_instruction = "You are Cosmo and you are talking to a friend."
dialogue_first = "Hey, how was your trip to Abu Dhabi?"

I tried
situation_narrative = "{{avatarName}} is having a friendly conversation with a friend."
role_instruction = "You are {{avatarName}} and you are talking to a {{humanName}}."
dialogue_first_avatar = "My name is {{avatarName}}."
dialogue_first_human = "My name is {{humanName}}."

Is there a better setup? I can't get "What is my name?" to work. Cosmo-xl thinks that I am Bill Gates. I am not Bill Gates. I am chatting with Bill Gates on www.justlearn.com

![Screenshot 2023-01-08 at 10 12 35](https://user-images.githubusercontent.com/39218132/211188549-f8ce74b1-dfde-45ea-a022-4a5d8812fafd.png)

**Comment by skywalker023** [comment]
Hello, we note that Cosmo is a simple dialogue model trained on SODA and ProsocialDialog mainly for academic/research purpose, so we do not encourage to use our model in real-world products as is. It has many practical limitations to be applied directly to real-world services.
