### ISSUE TITLE
Add search-server as fallback for dialogue

### ISSUE THREAD

**Issue by justlearntutors** [skywalker023/sodaverse#2]
Can you add search-server as fallback for dialogue like BlenderBot2?

Example
1 => "What are the latest news in Denmark"?
2 => AI check, if 1 => search else 0 => no search
3 => search = 1 => Search "lastest news in denmark" => Get text => Send text to sodaverse and sodaverse will rewrite text for the dialogue.

It will work good with search-server as fallback for sodaverse

Examples
https://github.com/JulesGM/ParlAI_SearchEngine
https://www.blenderbot.ai (Blenderbot3 with search-server, you need VPN or to be located in USA to test)

**Comment by justlearntutors** [comment]
Other examples
"What happened in year 1023?" => search=1
"What happened in year 3?" => search=1

**Comment by skywalker023** [comment]
COSMO is a simple model trained on SODA and ProsocialDialog mainly for research/academic purposes. Currently, we do not have plans for adding new features :)
