### ISSUE TITLE
Code for data set gen?

### ISSUE THREAD

**Issue by epec254** [skywalker023/sodaverse#9]
Are you planning to release this code?  I think your paper calls this CO2…

**Comment by skywalker023** [comment]
Hello, thank you for your interest in our project!
We will release our code after the EMNLP decision :)

**Comment by skywalker023** [comment]
We've just updated the code for CO_3! Thanks!

**Comment by skywalker023** [comment]
@epec254 We've just updated the code for CO_3! Thanks!
